In [2]:
import pandas as pd

In [3]:
data = {
    "Name": ["Vishal", "Rahul", "Priya", "Aman"],
    "Age": [21, 22, 20, 23],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore"],
    "Salary": [50000, 60000, 55000, 70000]
}
df = pd.DataFrame(data)

In [4]:
df

     Name  Age       City  Salary
0  Vishal   21      Delhi   50000
1   Rahul   22     Mumbai   60000
2   Priya   20       Pune   55000
3    Aman   23  Bangalore   70000

In [5]:
#for seeing starting values
df.head(2) #syntax --)df.head(n) where n is number of rows

     Name  Age    City  Salary
0  Vishal   21   Delhi   50000
1   Rahul   22  Mumbai   60000

In [6]:
#and same as for tail only difference is tail is used to see last value
df.tail(2)

    Name  Age       City  Salary
2  Priya   20       Pune   55000
3   Aman   23  Bangalore   70000

In [7]:
df.iloc[1:3 , :2] #in this we can access certain columns but keep in mind iloc is for location index(numerical) , and loc is for label
#syntax --> rows , column

    Name  Age
1  Rahul   22
2  Priya   20

In [8]:
#now we use loc when when are fetching rows 1 or 2 certain columns
df.loc[1:3 , ["Age" , "City"]]

   Age       City
1   22     Mumbai
2   20       Pune
3   23  Bangalore

In [9]:
# For accessing particular columns in df we have the following syntax
df['Age']#for accessing single column use 1d array and for accessing more than one column use 2d array

0    21
1    22
2    20
3    23
Name: Age, dtype: int64

In [11]:
#for accessing multiple columns we place the column names in a 2d array
df[['Name' , 'Age' , 'City']]

     Name  Age       City
0  Vishal   21      Delhi
1   Rahul   22     Mumbai
2   Priya   20       Pune
3    Aman   23  Bangalore

In [ ]:
#deleting or droping columns
df.drop(0 , axis = 0)

#for deleting rows we need to provide either index label or index name in the following syntax
#df.drop(numerical index or index label , axis = 0)

#for deleting columns we need to provide the column name and axis = 1
#df.drop(column_name , axis = 1)

#inplace parameter mean perform operation on original dataframe and changes will be permanent

    Name  Age       City  Salary
1  Rahul   22     Mumbai   60000
2  Priya   20       Pune   55000
3   Aman   23  Bangalore   70000

In [15]:
#checking shape of dataset
df.shape

(4, 4)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Salary  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

In [ ]:
df.describe()
#in output 25% , 50% , 75% are basically the outliers

             Age        Salary
count   4.000000      4.000000
mean   21.500000  58750.000000
std     1.290994   8539.125638
min    20.000000  50000.000000
25%    20.750000  53750.000000
50%    21.500000  57500.000000
75%    22.250000  62500.000000
max    23.000000  70000.000000

In [23]:
#broadcasting in pandas
#columns are also known as features

#increase salary by 5000
df['Salary'] = df['Salary'] + 5000
df['Salary']

0    60000
1    70000
2    65000
3    80000
Name: Salary, dtype: int64

In [27]:
#Renaming a column
df.columns
df.rename(columns= {'Name' : 'Good_Name'} , inplace = True)
df['Good_Name']

0    Vishal
1     Rahul
2     Priya
3      Aman
Name: Good_Name, dtype: object

In [28]:
#unique valued for a particular for a column
df['Salary'].unique()

array([60000, 70000, 65000, 80000])

In [ ]:
#checking count of every individual element
df['Salary'].value_counts()

Salary
60000    1
70000    1
65000    1
80000    1
Name: count, dtype: int64

In [32]:
#creating new columns
df['Promoted_salary'] = df['Salary'] * 10
df['Promoted_salary']

0    600000
1    700000
2    650000
3    800000
Name: Promoted_salary, dtype: int64